version: "3.8"
services:

  app:
    restart: on-failure
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      APP_DOMAIN_NAME: http://localhost:8080/
      MONGO_DB_URI: mongodb://localhost:27017

  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
